@host = http://localhost:8080

### 1. 상품 가입
# withdraw_account_id는 Account.http에서 저장한 값 사용
# desiredAccountNumber는 11자리 입력
# @name registSubscription
POST {{host}}/api/subscriptions
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "memberId": 1,
  "productId": 1,
  "withdrawAccountId": {{withdraw_account_id}},
  "principalAmount": 100000,
  "desiredAccountNumber": "12345678901"
}

> {% client.global.set("sub_id", response.body.data.id); %}

### 2. 가입 내역 전체 조회
GET {{host}}/api/subscriptions?memberId=1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### 3. 가입 상세 조회 및 예상 이자 확인
GET {{host}}/api/subscriptions/{{sub_id}}/interest
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### 4. 상품 중도 해지
POST {{host}}/api/subscriptions/{{sub_id}}/cancel
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "memo": "급전이 필요하여 중도 해지합니다."
}